### PR TITLE
[Products/SiteAccess] handle wildcard on rewrite url

### LINKED ISSUE #317: SiteAccess : feature request, replace wildcard in virtual url by host sub domain name
Hello,

I want to allow VirtualHostMonster to replace wildcard in virtual url by host sub domain name,
which we'll need in our project, here some example:
`/VirtualHostBase//https/couscous.example.org:443/folder/*//VirtualHostRoot/`
will render `/folder/couscous/`  with url `https://couscous.example.org/`
I already modify my zope and have a working demo, is it something wanted for you?
Could i open a pull request to discuss about that ?

Regards.

### PR DESCRIPTION
**Pull request by ZeddZull**
Fixes #317

### CODE REVIEW

**Comment by icemac** [comment]
@tseaver Do you agree to the implementation? Do you think this change requires signing a contributor agreement?

**Comment by ZeddZull** [comment]
@icemac @tseaver  is it enought ?

**Comment by icemac** [comment]
@ZeddZull I am going to merge your PR when the build is green.

**Comment by icemac** [comment]
@ZeddZull Thank you!

**Pull request merged**
