### PR TITLE
Remove Python 2.6 support and skip ipv6 test on Travis

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes issue #46.

Once this is accepted and merged, we can try pull request #45 again.

### CODE REVIEW

**Comment by tseaver** [comment]
Could we just skip the test on Travis, e.g. via something like:

```python
    if not os.environ.get('TRAVIS'):
        def test_http_over_ipv6(self):
```

**Comment by thet** [comment]
Shouldn't deprecated Python 2.6 support be dropped at all for Zope 4? Then we could use the nicer ``@unittest.skip`` and save some headache when encountering other Python 2.6 incompatibilities.

**Comment by mauritsvanrees** [comment]
I have removed Python 2.6 from `.travis.yml` and `setup.py`. Seems fair enough for Zope 4.

I have updated the pull request to use `unittest.skipIf` and check the os environment for `TRAVIS`, which according to the docs should indeed be there.

**Comment by tseaver** [comment]
@mauritsvanrees Thank you!

**Comment by mauritsvanrees** [comment]
@tseaver Thanks for reviewing and merging!

**Pull request merged**
