### PR TITLE
Revise sub-sections about argument marshalling.

### PR DESCRIPTION
**Pull request by jugmac00**
- fix typos
- improve doc string
- improve formatting

modified:   docs/zdgbook/ObjectPublishing.rst

### CODE REVIEW

**Comment by jugmac00** [comment]
Free beer to anybody who can show me the code where "URL0", "URL1", "URL2"... "URLPATHn", "BASEPATHn" and the likes get set (please add a link to the source code).

**Comment by dataflake** [comment]
I believe the code to set `BASE` and `URL` variables is here:

https://github.com/zopefoundation/Zope/blob/e82a33aa90578941d76905a87f63d8d73f71e7de/src/ZPublisher/HTTPRequest.py#L1452-L1466

**Comment by dataflake** [comment]
By the way, I also searched for `BASEPATH` and `URLPATH`. They show up in the code in a few places, but I have not found code that actually sets those on the Request object, and if you render a Request object they aren't there.

**Comment by jugmac00** [comment]
> By the way, I also searched for `BASEPATH` and `URLPATH`. They show up in the code in a few places, but I have not found code that actually sets those on the Request object, and if you render a Request object they aren't there.

Thanks for the update! Fix comes with #555

**Comment by jugmac00** [comment]
> I believe the code to set `BASE` and `URL` variables is here:
> 
> [Zope/src/ZPublisher/HTTPRequest.py](https://github.com/zopefoundation/Zope/blob/e82a33aa90578941d76905a87f63d8d73f71e7de/src/ZPublisher/HTTPRequest.py#L1452-L1466)
> 
> Lines 1452 to 1466 in [e82a33a](/zopefoundation/Zope/commit/e82a33aa90578941d76905a87f63d8d73f71e7de)
> 
>  # Cache URLN and BASEN in self.other. 
>  # This relies on a side effect of has_key. 
>  n = 0 
>  while 1: 
>      n = n + 1 
>      key = "URL%s" % n 
>      if key not in self:  # NOQA 
>          break 
>   
>  n = 0 
>  while 1: 
>      n = n + 1 
>      key = "BASE%s" % n 
>      if key not in self:  # NOQA 
>          break

@dataflake  Thank you! Shame on me. I only grepped for occourences in combination with + :-)

Hm, and I do not really get a grasp of the code snippets.

The local variable key gets something assigned, but afterwards key is no longer used. Hm... except the "in" operator has a side effect, the code snippet imho is a noop.

**Pull request merged**
