### PR TITLE
Issue 29

### PR DESCRIPTION
**Pull request by drfho**
Hi @dataflake, referring to #29 I added an initially reduced preview of long error texts; the view toggles per click. 

long_alerts

PS: please excuse the code mixing with my last pull request #582

### CODE REVIEW

**Comment by dataflake** [comment]
The functionality is exactly what I'm thinking of.

Do you think a visual cue that tells the user "there's more information, click me to see it" that's more obvious than just the slider at the right would be helpful?

**Comment by drfho** [comment]
hi @dataflake 
okay, now for the `<pre>`-case a line-break threshold will implant a visual clue for expanding the box: https://github.com/zopefoundation/Zope/pull/583/commits/49decbf08746c5a6f0d3bf6b5f81342de582e7f0
alertbox

**Comment by dataflake** [comment]
That looks more obvious, yes, thanks a lot. When Travis CI has gone through I will merge.

**Comment by dataflake** [comment]
@drfho I'm having issues on all my browsers on macOS. The chevron doesn't render, see screen shot. What's worse, clicking on the chevron or on the bar does not work at all in Firefox.

Screenshot

**Comment by drfho** [comment]
@dataflake 
now tested for FF: 
https://github.com/zopefoundation/Zope/commit/c4ab498e37b292a83a35ad9948017cb090791bbd

**Comment by dataflake** [comment]
Where did you put that code? I had deleted the branch already. It's not on master, right?

**Comment by dataflake** [comment]
I found it, there's a new branch

**Comment by dataflake** [comment]
It works now, but please no more branches without a PR attached like that newly creates issue_29. I had to do everything by hand. Merging failed with conflicts. I had to cherry-pick the one commit.

**Comment by drfho** [comment]
Sorry for that, seems that Eclipse mislead me and it was mixed up (I mentioned it in the first comment). So, would you please so kind to delete branch "issue_29" after merging? Thanks a lot.

**Comment by dataflake** [comment]
It's already gone😉

**Pull request merged**
