### PR TITLE
Port whitelist creation from zope.browserpage

### LINKED ISSUE #397: BrowserViews implement IPublishTraverse in Zope 4 which breaks allowed_attributes and allowed_interface
In Zope 4 a `BrowserView` always implements `IPublishTraverse` which it did not in Zope 2.
This breaks the way to make methods traveseable using `allowed_attributes` and `allowed_interface` in zcml. 

Example:

```xml
  <browser:page
      name="foo"
      for="*"
      class=".dummy.Foo"
      permission="zope2.View"
      allowed_attributes="bar"
      />
```
dummy.py:

```python
from Products.Five import BrowserView

class Foo(BrowserView):

    def __call__(self):
        return 'foo'

    def bar(self):
        """bar"""
        return 'foobar'
```

In Zope 2 (Plone 5.1) http://0.0.0.0:8080/Plone/foo/bar returned `foobar`. In Zope 4 (Plone 5.2) that throws a 404.

The relavant code is in `BaseRequest.traverseName`:

```python
if IPublishTraverse.providedBy(ob):
    ob2 = ob.publishTraverse(self, name)
else:
    adapter = queryMultiAdapter((ob, self), IPublishTraverse)
    if adapter is None:
        # Zope2 doesn't set up its own adapters in a lot of cases
        # so we will just use a default adapter.
        adapter = DefaultPublishTraverse(ob, self)

    ob2 = adapter.publishTraverse(self, name)
```

In Zope 4 `IPublishTraverse.providedBy(ob)` is true for all BrowserViews because in https://github.com/zopefoundation/Zope/blob/master/src/Products/Five/browser/metaconfigure.py#L145 the class `zope.browserpage.metaconfigure.simple` is injected in the `bases` of each `BrowserView`. Since `Foo` has no `publishTraverse` of its own the one from `simple` is called which then raises `NotFound`.

The `mro` looks like this before the injection:

```
(Pdb++) pp ob.__class__.__mro__
(<class 'Products.CMFPlone.browser.dummy.Foo'>,
 <class 'Products.Five.browser.BrowserView'>,
 <class 'zope.publisher.browser.BrowserView'>,
 <class 'zope.location.location.Location'>,
 <class 'object'>)
```

And like this after it:
```
(Pdb++) pp ob.__class__.__mro__
(<class 'Products.Five.browser.metaconfigure.Foo'>,
 <class 'Products.CMFPlone.browser.dummy.Foo'>,
 <class 'Products.Five.browser.BrowserView'>,
 <class 'Products.Five.browser.metaconfigure.simple'>,
 <class 'zope.browserpage.metaconfigure.simple'>,
 <class 'zope.publisher.browser.BrowserView'>,
 <class 'zope.location.location.Location'>,
 <class 'object'>)
```

@jaroel and me were trying to figure out a solution but we require help. 

*This issue is a replacement for the original ticket https://github.com/plone/Products.CMFPlone/issues/2624 which I moved to Zope since it is not directly related to Plone.*

### PR DESCRIPTION
**Pull request by pbauer**
Together with https://github.com/zopefoundation/zope.browserpage/pull/7 this fixes #397.

All Plone tests are green with that (see https://github.com/plone/buildout.coredev/pull/588)

Open points:

- [x] Implement a pair of tests using `allowed_interface`.

### CODE REVIEW

**Comment by icemac** [comment]
In #610 @jaroel requested to be able to have a custom `IPublishTraverse` adapter. IMHO this is not solved by this PR. Is this request still valid?

**Comment by icemac** [comment]
I ported the tests from branch `issue_397` here but the test for accessing the allowed attribute fails. Am I missing a part of the solution?

**Comment by MatthewWilkes** [comment]
Okay, I've fixed that failing test and cleaned up the implementation a bit. Rather than relying on replacing `__call__` I've moved the implementation of `browserDefault` from the metaconfigure directive into the simple class and added code to handle the changing attribute to avoid having to rebind the function.

I'm waiting for the Plone tests to finish, but I'm hopeful.

**Comment by MatthewWilkes** [comment]
@jaroel Can you clarify how important a usecase you think the publish traverse adapter is? It's possible to add a `publishTraverse` method directly to a view, but if we really need to support adapter based things I think we can. We'd probably need to add an adapter lookup in the publishTraverse of the simple class that looks up the adapter on the relevant baseclass.

**Comment by jaroel** [comment]
@MatthewWilkes , @icemac,
I mainly said that because in Plone+Zope2 a Browserview doesn't implement IPublishTravese, which in turn make the publisher query for an adapter, or use a fallback.
The latter is why the sub path traversal worked in the first place.

I'm unaware of code that uses the IPublishTraverse-as-adapter approach, so the current approach should work just fine by the looks of it.

**Comment by icemac** [comment]
This PR looks okay to me, I think a test for `allowed_interface` should be added for completeness. After the explanation of @jaroel I think we could drop the requirement of using a adapter. It could be added later if there is an actual demand.

**Comment by icemac** [comment]
zopefoundation/zope.browserpage#7 currently fails.

**Comment by MatthewWilkes** [comment]
@icemac Yep, it does. I've not had a chance to look at this again yet, but my instinct is that the problem is the test, not the code. It's testing that `browserDefault is None` as a way of identifying a misconfigured view, but I'm not convinced that is legitimate. We could likely add a special case for that, but I'd probably approach it by making the test more closely resemble the traversal/publishing flow.

**Comment by pbauer** [comment]
I have no real idea if the code is wring or the test. But in https://github.com/zopefoundation/zope.browserpage/pull/7/commits/6ab51664571511cedd1190f7882e8fce1cceaaa7 I attempted to adapt the test to show what's actually going wrong with the misconfigured view.

**Comment by icemac** [comment]
After zopefoundation/zope.browserpage#7 is accepted, merged and released. The `do not merge` label can be dropped here.

**Pull request merged**
