### PR TITLE
fix for #505: no special handling for single `filtered_meta_types` in…

### LINKED ISSUE #505: "App:dtml/manage_navbar.dtml": improper handling of single addable meta type
`manage_navbar.dtml` contains
```
<select id="addItemSelect" class="form-control-sm" name=":action"
  data-title-active="Select type to add"
  data-title-inactive="STATUS INACTIVE: New Object can only be Added in the List View"
  title="Select type to add"
  onchange="addItem( elm=this, base_url='<dtml-var "REQUEST.get('URL1','')">'); this.selectedIndex = 0;"
  ><option value="" selected="selected">Select type to add</option>
  <dtml-if "_.len(filtered_meta_types) > 1"
    ><dtml-in filtered_meta_types mapping sort=name
      ><dtml-if action><option value="&dtml.html_quote-action;">&dtml-name;</option>
      </dtml-if
    ></dtml-in
  ></dtml-if>
</select>
```
Obviously,  no add type to select is shown, if `filtered_meta_types` returns a sequence with just one element. Upfront logic make the element inactive in this case.

Zope 2 handled the case "len(filtered_meta_types) == 1" specially by replacing the "select type to add" directly by an "add XXXX" control in this case. While this is nice, the case is sufficiently rare that in my view its special casing is not mandatory. Therefore, I suggest to remove the `<dtml-if "_.len(filtered_meta_types) > 1">`.

### LINKED ISSUE #506: "zmi/styles/resources/zmi_base.js" allows adding content objects only if there is a "manage_findForm" action
I have difficulties to understand the associated comment (in `zmi_base.js`) `[1] Showing some Menu Elements only on List Page as Active`: how is the notion "List Page" related to a "manage_findForm" action?

### PR DESCRIPTION
**Pull request by d-maurer**
… `App.dtml.manage_navbar.dtml`

fix for #506: generate the `addItemSelect` form only for a context with unacquired `filtered_meta_types`

The pull request fixes #505 by not special casing "len(filtered_meta_types) == 1".

The pull request fixes #506 by replacing the fragile recognition of a "List page" in `zmi:styles/resources/zmi_base.js` by generating the `addItemSelect` form only for contexts with unacquired `filter_meta_types`.

### CODE REVIEW

**Comment by dataflake** [comment]
This appears to work for all cases I have looked at in a stock Zope 4 install and is certainly a much more robust solution. It does introduce a change in behavior, though, and that's why I'd like @drfho to weigh in. With this solution the entire widget disappears instead of just being disabled. I'm OK with that because it makes it even more clear that nothing can be added.

**Comment by dataflake** [comment]
@d-maurer Could I ask you to create a branch inside zopefoundation/Zope instead of working off a fork? That way it is much easier to cooperate on a fix.

**Comment by d-maurer** [comment]
@drfho, @dataflake

drfho wrote at 2019-2-16 09:17 -0800:
> ...
>Hi @d-maurer, @dataflake ,
>I am okay with breaking the 'law of monotony' here and removing the gui element by  creating (form the user's point of view)  case-by-case presentation of the addItem-list - in this case.

If you prefer,
it would be easy to create an empty "addItemSelect" - and make it passive
directly in the tamplate, instead of removing it completely.



--
Dieter

**Comment by d-maurer** [comment]
@dataflake, @drfho

Jens Vagelpohl wrote at 2019-2-16 09:53 -0800:
>@d-maurer Could I ask you to create a branch inside zopefoundation/Zope instead of working off a fork? That way it is much easier to cooperate on a fix.

I have copied the branch to
"https://github.com/zopefoundation/Zope/tree/zmi-add-fix-%23505%2B%23506"

**Comment by d-maurer** [comment]
@drfho, @dataflake,

drfho wrote at 2019-2-16 09:17 -0800:
> ...
>Because I do not see your pull request by GIT I appended the corrected dtml file here - sorry for that inconvenience. Please, can you merge it?

Following Jens' advice, I have copied my branch to
"https://github.com/zopefoundation/Zope/tree/zmi-add-fix-%23505%2B%23506".
This way, you should be able to directly work on it.

I will soon close my pull (old) request and make a new one
for the new branch.

**Comment by d-maurer** [comment]
Replaced by PR #508

**Comment by d-maurer** [comment]
@drfho, @dataflake

drfho wrote at 2019-2-16 09:17 -0800:
> ...
>Hi @d-maurer, @dataflake ,
>I am okay with breaking the 'law of monotony' here and removing the gui element by  creating (form the user's point of view)  case-by-case presentation of the addItem-list

I just recognized that the change in behaviour is apparent only.
The "addItemSelect" was already missing before my change
in case the current context had no "filtered_meta_types"
or it returned 0 elements.
My change has just prevented to get inadvertantly an acquired
"filtered_meta_types".


As mentioned earlier, it would be easy to get a (potentially disabled)
"addItemSelect" in all cases.

**Comment by drfho** [comment]
hi @d-maurer, @dataflake 
thank you, actually I prefer the potentially disabled gui element.
In https://github.com/zopefoundation/Zope/tree/issue_490 I remove the above mentioned HTML-errors, and rearranged your DTML in the sense of gui monotony (without JS)
@dataflake please, take a look at it and decide form a third persons view whether UX is better with or without the disabled addItem-selector.

**Comment by dataflake** [comment]
It looks fine to me, thanks for the additional work on it. At this point I'm just waiting for Dieter to confirm that the URL handling works for him, then I'll merge it.

**Pull request closed without merging**
