### PR TITLE
Fix bug when getting propertysheet and bugs in manage_FTPlist

### PR DESCRIPTION
**Pull request by pbauer**
Fixes bug introduced in https://github.com/zopefoundation/Zope/commit/b4495eb403c622300b02071a0904b3ad948cc4fe?diff=unified&w=1#diff-3bb20756c73e7cac2fb14728c89e578aR472

### CODE REVIEW

**Comment by pbauer** [comment]
This fixes 3 of the 6 failing tests in https://github.com/plone/buildout.coredev/pull/586

**Comment by jugmac00** [comment]
I am +1 for writing at least a very minimal test. This regression could only be introduced as there was no test.

**Comment by jensens** [comment]
> I am +1 for writing at least a very minimal test.

Indeed a valid point!

**Comment by pbauer** [comment]
The second commit fixes this failing test:

```
Failure in test /Users/pbauer/.cache/buildout/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers_zserver.rst
Failed doctest test for layers_zserver.rst
  File "/Users/pbauer/.cache/buildout/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers_zserver.rst", line 0

----------------------------------------------------------------------
File "/Users/pbauer/.cache/buildout/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers_zserver.rst", line 94, in layers_zserver.rst
Failed example:
    ftpClient.retrlines('LIST')
Expected:
    drwxrwx---   1 test_user_1_ Zope            0 ... .
    d---------   1 admin        Zope            0 ... ..
    '226 Transfer complete'
Got:
    drwxrwx---   1 test_user_1_ Zope            0 May 13 09:42 .
    '226 Transfer complete'
```

**Comment by pbauer** [comment]
The last commit (https://github.com/zopefoundation/Zope/pull/624/commits/a764822be14a5f9ec6bdbd4b330601303b441256) fixed:

```
Failure in test /Users/pbauer/.cache/buildout/eggs/plone.testing-7.0.1-py2.7.egg/plone/testing/zserver.rst
Failed doctest test for zserver.rst
  File "/Users/pbauer/.cache/buildout/eggs/plone.testing-7.0.1-py2.7.egg/plone/testing/zserver.rst", line 0

----------------------------------------------------------------------
File "/Users/pbauer/.cache/buildout/eggs/plone.testing-7.0.1-py2.7.egg/plone/testing/zserver.rst", line 616, in zserver.rst
Failed example:
    ftpClient.retrlines('LIST')
Expected:
    drwxrwx---   1 Zope     Zope            0 ... .
    ...--w--w----   1 Zope     Zope            0 ... acl_users
    drwxrwx---   1 Zope     Zope            0 ... folder1
    '226 Transfer complete'
Got:
    --w--w----   1 Zope     Zope            0 May 13 10:01 acl_users
    '226 Transfer complete'
```

**Comment by dataflake** [comment]
@pbauer Yes, a minimal test would be nice, and fixing the flake8 tests that fail now.

**Comment by pbauer** [comment]
A test would be nice indeed but It was a mayor effort to find the time to find and fix these last failing test in Plone with Zope 4.0 and I won't have much time in the next days. Can we please merge this and please have a Zope 4.0.1 release soon? We've already had to postpone the release of Plone 5.2 because of these issues.

**Comment by pbauer** [comment]
Thanks!

**Pull request merged**
