### PR TITLE
Restore the ZMI `Debug Information` control panel page

### LINKED ISSUE #898: Restore debug support via "Control_Panel"?
## Question/Enhancement
I am currently investigating a memory leak in Zope 2. Its "Debug information" in `Control_Panel` is valuable help (even though I had to replace `App.ApplicationManager.DebugManager.refcount` to avoid `six` problems). This functionality has been removed from Zope 4.

Should this functionality (as well as cache analysis and open connection overview) be restored
in stock Zope?

The alternative is that I make corresponding analysis tools available via a package `dm.zope.debug` -- usable for anyone who find them useful.

Zope 4.x, Zope 5

### PR DESCRIPTION
**Pull request by dataflake**
Fixes #898 

This PR adds a "Debug Information" page to the control panel. This Debug Information page restores those parts of the old Zope 2  DebugInfo page that are not already presented on other control panel tabs.

The trickiest part was finding a place to add the request debugging information for running requests that shows up at the bottom of the page where the database connection information is. I have added it inside the WSGI publisher code. This used to be done by the `App.ZApplication.ZApplicationWrapper.__bobo_traverse__`, but that method is only called by the old ZServer publisher.

The ZMI bits could use some prettification, but functionally it's all there.

### CODE REVIEW

**Review by d-maurer — APPROVED** [review]
Good!
It has been a very good idea to move the `sys.path` information out of "Debug Information".

I have not changed the `t` parameter of the method `refcount` (even though this might be necessary to analyze memory leaks in "modern" Zope applications). I would like to await concrete experience from my current memory leak analysis and its trial definition `(ExtensionClass, type, ClassType)`: it could be possible that the refcount information for types implemented in C does not give a good estimate for the number of type instances.

**Comment by d-maurer** [comment]
> ...
> it could be possible that the refcount information for types implemented in C does not give a good estimate for the number of type instances.

This is indeed the case (both Python 2 and Python 3):
```pycon
>>> from sys import getrefcount as rc
>>> l=[str(x) for x in range(1000)]
>>> rc(str)
73
```
I applies also for classes derived from elementary Python data types:
```pycon
>>> class C(dict): pass
... 
>>> l=[C() for x in range(1000)]
>>> rc(l)
2
```
For old style classes (Python 2) and "normal" classes, the class refcount gives a good estimation for the number of instantiated objects:
```pycon
>>> class C(object): pass
... 
>>> l=[C() for x in range(1000)]
>>> rc(C)
1005
>>> class O: pass
... 
>>> l=[O() for x in range(1000)]
>>> rc(O)
1002
```

**Comment by icemac** [comment]
I would have liked to restart the failing job on TravisCI as it seems to be a timing issue, but I am currently (no longer?) be allowed to do so.

**Comment by icemac** [comment]
I've never actually used this feature so I am removing me from the reviewers list.

**Comment by dataflake** [comment]
> I would have liked to restart the failing job on TravisCI as it seems to be a timing issue, but I am currently (no longer?) be allowed to do so.

Nothing changed at Travis as far as I know. Did you log into Travis from that job status page? You won't see the buttons to restart a job if you're not logged in.

**Comment by icemac** [comment]
@dataflake wrote:
> Nothing changed at Travis as far as I know. Did you log into Travis from that job status page? You won't see the buttons to restart a job if you're not logged in.

I am logged in at https://travis-ci.org via Github. In Settings I see the Zope project but if I try to go to its settings I get „Your permissions are insufficient to access this repository's settings“. Re-Login did not help. Maybe they screwed up their database a bit.

Is there a reason why we are still at travis-ci.org instead of travis-ci.com?

**Comment by d-maurer** [comment]
I have now practical experience with `App.ApplicationManager.DebugManager.refcount` collecting not only refcount information for `ExtensionClass` instances but also for normal classes (i.e. instances of `six.class_types`). That extended information is useful for memory usage analysis if one is aware that the collected refcounts are not for all classes a good estimate for the number of class instances (this applies in particular for elementary Python data types and their derived classes). As a consequence, I have added `six.class_types` to the refcount `t` parameter.

**Comment by dataflake** [comment]
> I am logged in at https://travis-ci.org via Github. In Settings I see the Zope project but if I try to go to its settings I get „Your permissions are insufficient to access this repository's settings“. Re-Login did not help. Maybe they screwed up their database a bit.

I can log in and view those settings fine. I then looked if I am member of any GitHub team under zopefoundation/Zope that you're not and added you to "Contributors" - maybe that makes a difference.

> Is there a reason why we are still at travis-ci.org instead of travis-ci.com?

Not that I know. I didn't set this up. Feel free to move it.

**Comment by icemac** [comment]
> I can log in and view those settings fine. I then looked if I am member of any GitHub team under zopefoundation/Zope that you're not and added you to "Contributors" - maybe that makes a difference.

Now I again have the ability to restart Travis jobs. Thank you, although I am not sure if adding me to Contributors caused the change.

**Comment by dataflake** [comment]
Neither am I 🙄

**Pull request merged**
