### PR TITLE
Update to newest compatible versions of dependencies.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Tests pass, except on MacOS. That is a known problem in ZCatalog. I am trying a PR to fix that:
https://github.com/zopefoundation/Products.ZCatalog/pull/141

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
Looks like the ZCatalog changes helped.

**Comment by mauritsvanrees** [comment]
Your merge of master reminds me that I need to update the constraints/requirements too. Done. I will merge if it stays green.

**Comment by mauritsvanrees** [comment]
There was a different [ZCatalog error on Mac Py 3.7](https://github.com/zopefoundation/Zope/actions/runs/3689677356/jobs/6245894691#step:6:539). I reran this job and it passed.

I merge.

**Comment by mauritsvanrees** [comment]
After merge, the Mac 3.9 job failed. I have opened a new issue:
https://github.com/zopefoundation/Products.ZCatalog/issues/142

**Pull request merged**
