### PR TITLE
Drop dependency on six.

### PR DESCRIPTION
**Pull request by icemac**
See #692

### CODE REVIEW

**Comment by karpierz** [comment]
Hi Michael
Can I participate in porting zope to Py3?
I love Zope ;) (although I haven't used it for quite a long time) so... ?
Thanks
Adam

**Comment by icemac** [comment]
@karpierz Of course you can participate. Although Zope already runs on Python 3. Currently we are in the phase of dropping Python 2 support. You can take a ticket from the [5.0 milestone](https://github.com/zopefoundation/Zope/milestone/9). The repsitory policies require you to sign a contributor agreement, (see https://www.zope.org/developer/becoming-a-committer.html) which will allow you to assign issues to yourself and to get the changes merged that you'll make.

**Comment by jugmac00** [comment]
@icemac Do you know pyupgrade?

Maybe it could help you with this pr.
https://github.com/asottile/pyupgrade#remove-six-compatibility-code

**Comment by icemac** [comment]
@jugmac00 No, I was not aware of this pyupgrade feature. I'll give it a try.

**Pull request closed without merging**
