### PR TITLE
Test against Python 3.12a5.

### PR DESCRIPTION
**Pull request by icemac**
See #1085.
Using https://github.com/zopefoundation/meta/pull/195

### CODE REVIEW

**Comment by gforcada** [comment]
Note that since 2 days there's [a new alpha out](https://www.python.org/downloads/release/python-3120a6/) 😅 

According to the [release schedule](https://peps.python.org/pep-0693/) there will be a last alpha version in a month, and then we will start the beta process.

**Review by dataflake — APPROVED** [review]
The change is fine, but you'll need to add an exclusion for Python 3.12/macOS, similar to the existing exclusions for newer Pythons on macOS. See https://github.com/zopefoundation/meta/issues/181

**Comment by icemac** [comment]
> Note that since 2 days there's [a new alpha out](https://www.python.org/downloads/release/python-3120a6/)

I know but it is not available on GHA.

**Comment by icemac** [comment]
> The change is fine, but you'll need to add an exclusion for Python 3.12/macOS, similar to the existing exclusions for newer Pythons on macOS. See [zopefoundation/meta#181](https://github.com/zopefoundation/meta/issues/181)

See https://github.com/zopefoundation/meta/pull/195 where I implemented this "fix".

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
