### PR TITLE
Issues #729, #730: ZMI Security tab: Make permissions list fixed when scrolling left/right

### PR DESCRIPTION
**Pull request by drfho**
Hi @dataflake ,
 I added a JS check of the table size for jumping into the compressed/responsive view of that table, if it's standard/desktop view is too  broad for the window size. I think in most cases this will be perfect:
src/OFS/dtml/access.dtml
src/zmi/styles/resources/zmi_base.css

zmi_userperms_table

If the table is super-super-broad, a column fixing would be helpful, but in the mobile view, it does not work in general, because the the first two cols are too broad. So I need to think a little more about it. 
Anyway another modification will be added to the one shown here, so this change could be merged already.

Thanks for the hint.
Best regards
f

PS: Maybe you could add the .gitignore conf for ".vscode"?

### CODE REVIEW

**Comment by dataflake** [comment]
@drfho Friendly reminder: When you create a branch from `master`, **PLEASE** do a `git fetch` and a `git pull` first so your local `master` is fully up to date. I didn't notice that and kept adding commits on this branch before realizing what happened. I had to rebase the branch and fix a bunch of conflicts.

That said, this solution looks nice and works for me on Chromium and Firefox, but not on Safari. I'd also still like to add something like I suggested where you will always have the permission name in view, no matter how wide the table gets. In my case, we currently have about 50 roles...

**Comment by drfho** [comment]
Hi @dataflake,
seems we worked in parallel: actually I tried hard to display the first two cols of the permission table as fixed. But the table is too komplex; nothing worked.  So I added the permission-name to the title (as data-title, shown by CSS), similar to your proposal based on the standard-tooltip.

security

This is a simple solution and even your 50 roles case should work with it. 
Besides, I found out, that a normal HDMI screen shows the table with more than 40 roles, if you scale the viewport to 80%.

security_42roles

For some small css fixes  and the safari prob I will add a new PR on the base of your merged master.
Many thanks
f

**Comment by dataflake** [comment]
No, thank you for your work.

I expanded on the tooltip for the table cells with the checkbox by adding both the role and permission to it, by the way. I am happy with the way it is  now, just the Safari issueshould be fixed at some point.

Funny enough, in our specific setup much of the issue has disappeared with a pending complete rewrite of how that site handles roles and permissions, which brought it down to about 25 roles from several hundred.

**Comment by dataflake** [comment]
P.S.: Just noticed you had done the exact same thing with the tooltip, just formatted differently. Mine just used a line break in the title and qualifies both lines with what they are to be super clear.

**Comment by drfho** [comment]
yes, your variant is better.

**Pull request merged**
