### PR TITLE
Clean up and refactor version pin configurations

### PR DESCRIPTION
**Pull request by dataflake**
The goal for this PR is to remove any version pins that are no longer required and to distinguish better between what's really needed to install and run Zope (`versions-prod.cfg`) and what's purely optional or for development/testing (`versions.cfg`).

The `buildout.cfg` file still contains several things that could really go away. For example, the convenience of creating the script `bin/makedocs` instead of just using `pip` to install Sphinx and run `make html` inside the `docs` folder is causing maybe half of all dependencies listed in `versions.cfg`.

I also don't see why something like `ztktests` is needed, which tests ZTK packages separately, and I suspect some are not even Zope dependencies. And `alltests` pulls in and tests optional packages as well, all of which are already tested with automated testing in their own GH repositories.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have the same goal for Plone. Plone 6.0 is a step in this direction, but not entirely there. I expect more changes in 6.1, and if possibly a move to making the pip constraints leading, and derive the Buildout versions from there. See [Plone issue 3670](https://github.com/plone/Products.CMFPlone/issues/3670). So I like the direction.

Can you explain how you ended up at these versions?

I created a venv for Python 3.11 and one for 3.7 in sub directories and did `bin/pip install -e ..` (for 3.7: `pip install PasteDeploy==2.1.1 -e ..` for reasons given in `versions-prod.cfg`) and then a pip freeze. When I compare the output with the `constraints.txt` on this branch, I am missing these pins that should be added here:

```
WebTest==3.0.0
beautifulsoup4==4.11.1
six==1.16.0
soupsieve==2.3.2.post1
zodbpickle==2.6
```

And you have these extra pins that might be removed (from a pip viewpoint):

```
Zope2==4.0
zdaemon==4.4
zope.testrunner==5.6
```

**Comment by mauritsvanrees** [comment]
Removing Sphinx from the buildout should indeed by fine.

Same for ztktests, as it is not used. I see lots of errors when I try it:

```
...
    AttributeError: module 'zope' has no attribute 'security'
...
Total: 8584 tests, 11 failures, 469 errors and 55 skipped in 1 minutes 2.796 seconds.
```

For `alltests` I can see the use of testing several packages together with Zope, so incompatibilities are found before a release, so I would be in favour of keeping it. For Plone we have the Jenkins server where for each PR of a Plone package we run all tests of all packages, about 9000 of them.
But the list of extra packages here seems random now.
I wonder how often regressions are found this way.

**Comment by dataflake** [comment]
I used `zc.buildout` and not `pip` for my tests. I commented out everything in the versions files that was not explicitly listed as dependency in Zope's `setup.py`. Then I ran `bin/buildout install zopescripts` and iteratively added back all transitive dependencies in `versions-prod.cfg` that caused buildout errors because they were not pinned. Then I did the same with the other stanzas from `buildout.cfg`, but all those are clearly optional and belong into `versions.cfg`.

**Comment by icemac** [comment]
I'd like to make sure `bin/alltests` is kept as it is currently the only way to test Zope and usually used packages against new non-final Python versions before making releases.

The other changes seem okay to me.

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
Small detail: `zope-ecosystem.cfg` should be removed from `.meta.toml` and `MANIFEST.in`.

When I try it in the same way as you, starting with only `zopescripts` with `Zope[wsgi]` in it, I get a few differences:

```
$ git diff versions-prod.cfg
diff --git a/versions-prod.cfg b/versions-prod.cfg
index cd3f7090a..088cb74e1 100644
--- a/versions-prod.cfg
+++ b/versions-prod.cfg
@@ -19,8 +19,10 @@ Persistence = 3.6
 RestrictedPython = 6.0
 WSGIProxy2 = 0.5.1
 WebOb = 1.8.7
+WebTest = 3.0.0
 ZConfig = 3.6.1
 ZODB = 5.8.0
+beautifulsoup4 = 4.11.1
 cffi = 1.15.1
 multipart = 0.2.4
 persistent = 5.0
@@ -28,12 +30,15 @@ pycparser = 2.21
 python-gettext = 4.1
 pytz = 2022.7
 roman = 3.3
+six = 1.16.0
+soupsieve = 2.3.2.post1
 transaction = 3.0.1
 waitress = 2.1.2
 z3c.pt = 3.3.1
 zExceptions = 4.3
 zc.lockfile = 2.0
-zdaemon = 4.4
+zc.recipe.egg = 2.0.7
+zodbpickle = 2.6
 zope.annotation = 4.8
 zope.browser = 2.4
 zope.browsermenu = 4.4
@@ -74,7 +79,6 @@ zope.tal = 4.5
 zope.tales = 5.2
 zope.testbrowser = 5.6.1
 zope.testing = 5.0.1
-zope.testrunner = 5.6
 zope.traversing = 4.4.1
 zope.viewlet = 4.3
```

And then with the full buildout I get changes in versions.cfg:

```
$ git diff versions.cfg
diff --git a/versions.cfg b/versions.cfg
index dc16a5d48..86d2abb6e 100644
--- a/versions.cfg
+++ b/versions.cfg
@@ -15,9 +15,7 @@ Pygments = 2.14.0
 Record = 3.6
 ## Sphinx 6 requires docutils>18, clashes with sphinx-rtd-theme
 Sphinx = 5.3.0
-WebTest = 3.0.0
 alabaster = 0.7.12
-beautifulsoup4 = 4.11.1
 certifi = 2022.12.7
 ## requests 2.28.1 requires charset-normalizer <3
 charset-normalizer = 2.1.1
@@ -29,11 +27,10 @@ idna = 3.4
 imagesize = 1.4.1
 mock = 5.0.1
 mr.developer = 2.0.1
+packaging = 23.0
 plone.recipe.command = 1.1
 requests = 2.28.1
-six = 1.16.0
 snowballstemmer = 2.2.0
-soupsieve = 2.3.2.post1
 sphinx-rtd-theme = 1.1.1
 sphinxcontrib-applehelp = 1.0.2
 sphinxcontrib-devhelp = 1.0.2
@@ -42,13 +39,12 @@ sphinxcontrib-jsmath = 1.0.1
 sphinxcontrib-qthelp = 1.0.3
 sphinxcontrib-serializinghtml = 1.1.5
 tempstorage = 5.2
-urllib3 = 1.26.13
+urllib3 = 1.26.14
 z3c.checkversions = 1.2
-zc.recipe.egg = 2.0.7
 zc.recipe.testrunner = 2.2
-zodbpickle = 2.6
 zodbupdate = 1.5
 zope.componentvocabulary = 2.3.0
 zope.formlib = 5.0.1
 zope.ramcache = 2.4
 zope.sendmail = 5.3
+zope.testrunner = 5.6
```

So a few were moved, and a few are extra or missing.  This results in the following diff for the constraints:

```
g di constraints.txt
diff --git a/constraints.txt b/constraints.txt
index 40f2f6f04..d1e162ed4 100644
--- a/constraints.txt
+++ b/constraints.txt
@@ -14,9 +14,11 @@ Persistence==3.6
 RestrictedPython==6.0
 WSGIProxy2==0.5.1
 WebOb==1.8.7
+WebTest==3.0.0
 ZConfig==3.6.1
 ZODB==5.8.0
 Zope2==4.0
+beautifulsoup4==4.11.1
 cffi==1.15.1
 multipart==0.2.4
 persistent==5.0
@@ -24,12 +26,15 @@ pycparser==2.21
 python-gettext==4.1
 pytz==2022.7
 roman==3.3
+six==1.16.0
+soupsieve==2.3.2.post1
 transaction==3.0.1
 waitress==2.1.2
 z3c.pt==3.3.1
 zExceptions==4.3
 zc.lockfile==2.0
-zdaemon==4.4
+zc.recipe.egg==2.0.7
+zodbpickle==2.6
 zope.annotation==4.8
 zope.browser==2.4
 zope.browsermenu==4.4
@@ -70,6 +75,5 @@ zope.tal==4.5
 zope.tales==5.2
 zope.testbrowser==5.6.1
 zope.testing==5.0.1
-zope.testrunner==5.6
 zope.traversing==4.4.1
 zope.viewlet==4.3
```

Something is pulling in `beautifulsoup4`. Okay, this comes from WebTest. This is pulled in by zope.testbrowser. And this is a direct requirement of Zope.

BTW, I would be in favour of sorting it case insensitively. But I don't much mind.

**Comment by dataflake** [comment]
@mauritsvanrees I totally agree with your proposed changes and put them all in. I did keep the sorting the same, though.

I ended up keeping the `make-docs` buildout stanza because to build the documents you'd essentially have to install Zope again.

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
