### PR TITLE
allow (some) builtins as first element in a path expression

### PR DESCRIPTION
**Pull request by d-maurer**
This PR is one possible implementation for "https://github.com/zopefoundation/Zope/issues/863".

It interprets "some builtins" as:
 * in an untrusted context: the builtins from `AccessControl.safe_builtins`
 * in a trusted context: all Python builtins and those from `AccessControl.safe_builtins`

Thus, the set of allowed builtins is likely larger than that natively supported by `chameleon`. I believe that `chameleon` currently does not expose its set for external access; this would be necessary to ensure that the same set of builtins is supported.

### CODE REVIEW

**Comment by d-maurer** [comment]
Some builtins will be rejected because their name is not supported (e.g. starts with `_`).

**Comment by dataflake** [comment]
What are the security implications of this patch? Is it just making all those names available in path expressions that were already available in python expressions, or does it add a lot of additional access that wasn't available at all before?

**Comment by d-maurer** [comment]
> What are the security implications of this patch? Is it just making all those names available in path expressions that were already available in python expressions, or does it add a lot of additional access that wasn't available at all before?

I expect that now only builtins can be accessed as path expressions which formerly were
already accessible in Python expressions.

Behind this expectation are the following assumptions:

 * an unrestricted Python expression can access any Python builtin

 * a restricted Python expression can access any builtin from `AccessControl.safe_builtins` provided its name does not start with `_` (those are considered internal) (the restricted Python `ast` transformation rejects names starting with `_`).

I am quite sure that the second assumption is correct: as far as I know a restricted Python expression is first parsed into `ast` normally; the `ast` is then processed by the restricted Python transform - this transforms/checks as necessary (in particular, names starting with `_` are rejected); the result is evaluated with a copy of `AccessControl.safe_builtins` as "global dict" (and thus can access its builtins).

The path expression infrastructure enforces that the first element in a path expression has a legal variable name, especially does not start with `_`.

**Comment by dataflake** [comment]
Thanks for the explanation. I believe https://github.com/zopefoundation/Zope/issues/864 won't be affected by this patch because there's nothing "new" being added to whatever the different types of TAL expressions were already able to reach. Just trying to stay on top of the "big picture".

**Pull request merged**
