### PR TITLE
Fix broken ZMI pages due to the changed default content type

### LINKED ISSUE #1078: Bad Content-Type after merging #1075
Some ZMI pages don't render correctly after the last bugfix release because they never set an explicit `Content-Type` header and will now be published with the new default `text/plain`. Examples are:

- [ ] /manage_tabs
- [ ] /manage

There may be more.

### PR DESCRIPTION
**Pull request by dataflake**
Fixes #1078 

There may be more affected pages

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM. I clicked around in /manage_main and /manage and the Plone UI and did not find any further problems.

**Comment by d-maurer** [comment]
I checked DTML methods and documents, Script (Python), sessioning, PluggableAuthService -- no problems detected.

**Review by perrinjerome — APPROVED** [review]
Thanks @dataflake I'm sorry I missed this. I am also a `manage_main` user.

I took the time to click around with a default Zope 5.7.1 installation and did not find other pages with this problem.

**Comment by GiaBen** [comment]
On zope5.7.2 it looks like this page is not rendered: http://localhost:8080/Z_SQLite_Database_Connection/manage_edit


<HTML>
<HEAD>
<TITLE>Edited</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF">
<FORM ACTION="./manage_properties" METHOD="GET" >
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="10">
<TR>
  <TD VALIGN="TOP">
  <BR>
  <CENTER><B><FONT SIZE="+6" COLOR="#77003B">!</FONT></B></CENTER>
  </TD>
  <TD VALIGN="TOP">
  <BR><BR>
  <CENTER>
  <strong>Z_SQLite_Database_Connection</strong> has been edited.
  </CENTER>
  </TD>
</TR>
<TR>
  <TD VALIGN="TOP">
  </TD>
  <TD VALIGN="TOP">
  <CENTER>
  <INPUT TYPE="SUBMIT" VALUE="   Ok   ">
  </CENTER>
  </TD>
</TR>
</TABLE>
</FORM>
</BODY></HTML>

**Comment by dataflake** [comment]
Can you tell me the Zope add-on name that defines these database connections?

**Comment by perrinjerome** [comment]
I can reproduce this with https://github.com/nakagami/Products.ZSQLiteDA

**Comment by dataflake** [comment]
It looks like the (long outdated) `MessageDialog` class needs to manually set `Content-Type` as well.

**Comment by perrinjerome** [comment]
BTW, I have verified and Products.ZSQLMethods and Products.ZMySQLDA which looks OK.

The problem might be with https://github.com/zopefoundation/Zope/blob/25119a5ac7f783b7f59cd3dcaf2519676abeee65/src/App/Dialogs.py#L37 because https://github.com/nakagami/Products.ZSQLiteDA/blob/c89c190f9572070607893ee09f627c3862370905/Products/ZSQLiteDA/DA.py#L128-L133 is text/plain 

I can take a look

**Comment by dataflake** [comment]
In general, `MessageDialog` is a leftover from Zope 2 days and any use of it is strongly discouraged. It's seriously user-unfriendly with its interstitial-type dialogs that require a click-through. But it needs to be fixed for software that sees little or no real maintenance.

**Comment by GiaBen** [comment]
Please see Jérome cooments

**Comment by perrinjerome** [comment]
I see `MessageDialog` inherits from `HTML`, which is defined in https://github.com/zopefoundation/Zope/blob/6d399cc9392ba6bc29647c0bcdd4296e511bacc6/src/App/special_dtml.py#L49-L50 It uses `DocumentTemplate.HTML`, but `DocumentTemplate.HTML` does not set the header. It is only set at a higher level in 
https://github.com/zopefoundation/Zope/blob/1b9f2c73a1f37321b2ca0216333945ef2dfb71b6/src/OFS/DTMLDocument.py#L100-L106

I feel we could also make `App.special_dtml.HTML`  and  `App.special_dtml.ClassicHTMLFile`  set content type to `text/html`, because the class names are "HTML".

**Comment by dataflake** [comment]
I had one more report come in about the `standard_error_message` mechanism when using a DTML Method. Need to test that as well before a new release.

**Comment by dataflake** [comment]
I just released Zope 4.8.6 with fixes for MessageDialog and exception views, including the old `standard_html_error`. Waiting for some more feedback for my suggestion at https://github.com/zopefoundation/meta/issues/177#issuecomment-1357316282 before doing the next Zope 5 release.

**Pull request merged**
