### PR TITLE
Fix import sort order.

### PR DESCRIPTION
**Pull request by icemac**
This commit is mainly the result of `tox -eisort-apply`.
It makes the first part of the linting environments happy.

What do you think of it?
Is it worth the hassle?
Should the isort config be adapted?

### CODE REVIEW

**Comment by dataflake** [comment]
Can the isort configuration be adapted to our (informal) convention? Should we continue using such a convention?

```
import builtin1
from builtin2 import foo

import six
import other_thirdparty

from Acquisition import aq_base
from zope.library1 import bar

import localmodule
```

**Comment by dataflake** [comment]
For a customer project I have been using this configuration in `setup.cfg`:

```
[isort]
force_single_line = True
combine_as_imports = True
sections = FUTURE,STDLIB,THIRDPARTY,ZOPE,FIRSTPARTY,LOCALFOLDER
known_third_party = <e.g. six goes here>
default_section = ZOPE
line_length = 79
lines_after_imports = 2
not_skip =
    __init__.py
```

**Comment by dataflake** [comment]
What really annoys me is that there's no configuration to bunch "from..." and "import..." together. I'd really prefer something like this:

```
import foo
from foo.bar import baz
import zzz
```

**Comment by icemac** [comment]
I prefer having a single block of import statements sorted alphabetically case sensitive. This way I have to think least where an import has to be place: add it to the block sort the block using a keyboard shortcut and done.

I know there are many other habits so we have to decide on one or drop forcing the sort order of imports from the Zope project.

The one in https://github.com/zopefoundation/Zope/blob/master/setup.cfg#L13 is the one used in Plone projects, I think. (@loechel can you confirm this?)

**Comment by icemac** [comment]
@dataflake wrote:

> For a customer project I have been using this configuration in `setup.cfg`:
> 
> ```
> [isort]
> force_single_line = True
> combine_as_imports = True
> sections = FUTURE,STDLIB,THIRDPARTY,ZOPE,FIRSTPARTY,LOCALFOLDER
> known_third_party = <e.g. six goes here>
> default_section = ZOPE
> line_length = 79
> lines_after_imports = 2
> not_skip =
>     __init__.py
> ```

Looks interesting, although I'd prefer to merge `THIRDPARTY` and `ZOPE` as there are at least some packages used by Zope which are hard to decide and third party packages have to be listed.

Maybe you could try it out in a separate PR. There is a tox environment `isort-apply` so the isort config could be applied using `tox -eisort-apply`.

**Comment by dataflake** [comment]
With the configuration I pasted everything that is not specifically excluded will end up as ``ZOPE``. The only packages I would explicitly separate using ``known_thirdparty`` are those that aren't under the zopefoundation umbrella.

**Comment by dataflake** [comment]
I have created a second PR #529 off of current master with a configuration I talked about in here.

**Pull request closed without merging**
