### PR TITLE
Try out zc.buildout 3.1.0

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by dataflake** [comment]
The Windows failure seems to point to an incompatibility between `cffi` 1.17.0 and `setuptools` version 74. I bet if you pin `setuptools<74` it will work.

**Comment by dataflake** [comment]
The `cffi` folks have an open PR, but who knows how long they will take for a release: https://github.com/python-cffi/cffi/pull/118

**Comment by dataflake** [comment]
Is that new pin acceptable? If yes I would add it to the other templates as well.

**Review by mauritsvanrees — APPROVED** [review]

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
> Is that new pin acceptable? If yes I would add it to the other templates as well.

So you were right in https://github.com/zopefoundation/meta/pull/274 that `setuptools 74` is not yet usable. So this is fine for now until `cffi` has fixed the bug on their end.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
