### PR TITLE
Try to run the windows tests on GHA instead of AppVeyor.

### PR DESCRIPTION
**Pull request by icemac**
This PR is built on https://github.com/zopefoundation/meta/pull/105.

### CODE REVIEW

**Comment by icemac** [comment]
Hm, how did the tests run successfully on AppVeyor? There are multiple problems with windows using `\r\n` instead of `\n`.

**Comment by icemac** [comment]
Okay, now just the tests have to be fixed on windows.

**Comment by icemac** [comment]
After approval I'd change the required CI jobs in the settings to the new names.

**Review by dataflake — APPROVED** [review]
Fantastic work!  🎉

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
