### PR TITLE
support IStreamIterator as WSGI response body

### PR DESCRIPTION
**Pull request by gweis**
I had troubles returning an IStreamIterator instance when using the WSGIPublisher.

This PR makes sure that no non iterator methods like seek, len and str are called when publishing an IStreamIterator.

For 2.13 backport see: #27 

cheers

### CODE REVIEW

**Comment by tseaver** [comment]
@gweis can you apply the same updates to this branch?

**Comment by gweis** [comment]
No problem. Will have it ready by the weekend. (let me know if it's needed earlier)

**Comment by tseaver** [comment]
That should be fine, thanks!

**Comment by gweis** [comment]
@tseaver sorry for the delay. I have merged everything back on top of current master and incorporated all relevant updates from the 2.13 branch. I can also do a new pull request to clear up history if necessary. Tests are running file locally, but Travis fails due to some download errors. Is there a way to re-run a Travis build?

**Comment by tseaver** [comment]
I have triggered a rebuild on Travis.

**Comment by gweis** [comment]
thanks... seems like something is not working quite right today with downloading eggs. at least one test run completed successfully.

**Comment by tseaver** [comment]
Thank you!

**Pull request merged**
