### PR TITLE
add test for `tal:switch` - to verify #862

### PR DESCRIPTION
**Pull request by d-maurer**
This PR adds a test for `tal:switch` in relation to #862 .

Note that the test requires a new (upcoming) `chameleon` version to succeed. Do not merge until this version is used by `Zope`.

### CODE REVIEW

**Comment by dataflake** [comment]
@d-maurer Simply add the Chameleon checkout to `buildout.cfg` so running the buildout will fetch the correct branch and the test run, and then merge that into `4.x`. It is perfectly acceptable to have checkouts on the branch. The release manager is resposible for checking the buildout configuration and replacing it with a release version pin during the relase.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-7-5 23:06 -0700:
>@d-maurer Simply add the Chameleon checkout to `buildout.cfg` so running the buildout will fetch the correct branch and the test run, and then merge that into `4.x`. It is perfectly acceptable to have checkouts on the branch. The release manager is resposible for checking the buildout configuration and replacing it with a release version pin during the relase.

Thank you for the tip!

It will (initially) work in a PR development branch - but may fail in the
integrating 4.x branch -- when 2 branches want different checkouts.

As "github" (apparently) deletes development branches on merge,
it may also fail in a PR development branch.
For example: the current PR depends on the
`chameleon` branch `patch/fix-static-attrs`.
When @malthe merges it into `master`, it may no longer be available
for a checkout.
When I use the commit id (instead of the branch name),
then it becomes quite difficult for an integrator to determine
what is required in the integrating context.

**Comment by dataflake** [comment]
In this case there's just one Chameleon branch where Malthe is fixing issues (`patch/fix-static-attrs`) so there won't be any conflict yet.

Deleting development branches when a PR is merged is a repository-specific GitHub setting. I always delete those branches, they don't serve a purpose anymore and just clutter up the branch list when you need to look for a specific branch.

If Malthe's branch is gone it's a 2 second change to either switch the buildout source configuration here to use the `master` branch or to delete the checkout configuration altogether if a release has happened.

I just added the Chameleon checkout to the buildout configuration and will merge it all to 4.x now so this PR and any issue connected to it can be closed.

**Comment by malthe** [comment]
You could also just refer to the commit rather than the development branch.

On Github, the commit is attached to an internal namespace as part of the completed pull request so the commit object would not go away even on garbage collection.

**Comment by dataflake** [comment]
I didn't want to tie it to a specific commit because the branch is a moving target and you seem to be adding more fixes.

**Comment by malthe** [comment]
I have released Chameleon 3.8.1 with these changes:

3.8.1 (2020-07-06)
------------------

- Added code optimization to reduce sequential appends of static text.

- The `default` symbol in dynamic attributes is now
  symbolic. Previously, it was assigned the string value of the
  default attribute text. A similar change has been made for
  switch/case expressions.

- The built-in `attrs` dictionary of static element attributes now
  correctly works with `tal:define`, etc.

- Fix slice code generation compatibility issue on Python 3.9.

**Comment by dataflake** [comment]
Thank you Malthe, I have updated the version pins for Zope `4.x` and `master`

**Pull request merged**
