### PR TITLE
Updated ACE editor JS-lib using markdown mode for editing DTML

### PR DESCRIPTION
**Pull request by drfho**
Hello @dataflake,
referrring to your issue #489 "Bootstrap text editor great for everything else but hard to use for DTML" I updated the ACE-Editor-Lib and evaluated working with the markdown-mode  for the Zope DTML code.  It does not mark "invalid" HTML anymore and looks quite practicable:

ace_dtml

### CODE REVIEW

**Comment by dataflake** [comment]
Thanks for that update. It gets rid of a few errors, but most seem to remain (see screen capture).

screenshot

**Comment by drfho** [comment]
Many thanks for the hint: I revised the content_type guessing
https://github.com/zopefoundation/Zope/pull/496/commits/7e96d8a2d0737581635457c831b189027dc2544e

**Comment by dataflake** [comment]
I'm still getting the error flags. Could you try it yourself with this content (that's the default content from the old ``standard_error_message`` DTML method):

```
<html>
<head><title>Site Error</title></head>
<body bgcolor="#FFFFFF">

<dtml-if error_message>
 <dtml-var error_message>
<dtml-else>

  <h2>Site Error!!!</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: &dtml-error_type;</strong><br/>
      <strong>Error Value: &dtml-error_value;</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
      <dtml-if "error_type in ('KeyError','NameError')">
      <li>This resource may be trying to reference a
      nonexistent object or variable <strong>&dtml-error_value;</strong>.</li>
      </dtml-if>
      <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  <dtml-comment>
   Here, events like logging and other actions may also be performed, such as
   sending mail automatically to the administrator.
  </dtml-comment>

</dtml-if>

</body>
</html>
```

**Comment by drfho** [comment]
Maybe prohibitive caching? 
On my browser (Chrome/FF/Edge)  Your DTML-Code looks like this:

ace_dtml2

**Comment by dataflake** [comment]
Ah, yes, you're right, that was the problem. All happy now. Thanks for the work!

**Pull request merged**
