### PR TITLE
Translated part of the document into Japanese.

### PR DESCRIPTION
**Pull request by techtake**
Translated pages are follows.
- INSTALL.po
- index.po

You can check the result at the link below.
https://zope-doc-jp.readthedocs.io/ja/latest/index.html

### CODE REVIEW

**Comment by dataflake** [comment]
We can only accept contributions after you have signed the contributor agreement, please see https://www.zope.dev/developer/becoming-a-committer.html for details.

**Comment by techtake** [comment]
Thank you for the information. Let me confirm the agreement.

**Comment by dataflake** [comment]
Creating a branch is always better because it makes it easy for others to make changes on a PR. For example, I wanted to fix the cause for the failing lint check (see https://github.com/zopefoundation/Zope/actions/runs/4447026589/jobs/7808176639?pr=1108) but I can't. So if it isn't too much work for you please create a branch and close this PR.

Discussion on a PR or an an issue in the respective GitHub repository is fine.

**Comment by techtake** [comment]
Before closing this PR, I created a new branch (#1109-docs-ja-translation) and pushed files related to translation into Japanese.
https://github.com/zopefoundation/Zope/tree/%231109-docs-ja-translation

But I got the same test failure (ubuntu-lint) again.
https://github.com/zopefoundation/Zope/actions/runs/4476694913/jobs/7867322287#step:6:201
 
Could you help me to solve this?

**Comment by dataflake** [comment]
I can help you when you create the new PR and answer my question about the new files from https://github.com/zopefoundation/Zope/issues/1109#issuecomment-1477500477. The new files must be added to the manifest - but not all.

**Pull request closed without merging**
