### PR TITLE
Update zope.i18n to 4.8.0.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Plone uses this already.

### CODE REVIEW

**Comment by icemac** [comment]
@mauritsvanrees Is there a reason to keep this branch?

**Comment by dataflake** [comment]
How about turning on branch auto-deletion upon PR merge? It's active already in many of our repositories. I have never encountered a case where I want to keep a branch after merging.

**Comment by icemac** [comment]
@dataflake It is already active but it seems @mauritsvanrees manually restored the branch after it was automatically deleted.

**Comment by dataflake** [comment]
You're right, I see that now. My guess would be an unintended button press by Maurits...

**Comment by mauritsvanrees** [comment]
Looks like it. If I had a reason at that time, I have forgotten it, so it is fine that the branch is gone now. :-)

**Pull request merged**
