### PR TITLE
Add preliminary support for Python 3.12rc1.

### PR DESCRIPTION
**Pull request by icemac**
Let's try out the latest release. 

Locally it crashes with with a core-dump when running the tests before printing something useful.

### CODE REVIEW

**Comment by icemac** [comment]
My local failure looks like the GHA one: https://github.com/zopefoundation/Zope/actions/runs/5156707238/jobs/9288068396

**Comment by dataflake** [comment]
Locally, also on Python 3.12b0, I am seeing this:

```
$ bin/tox -epy312
py312: install_deps> python -I -m pip install cffi 'wheel>0.37' 'zc.buildout>=3.0.1'
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 326, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "/Users/jens/src/zope/Zope/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by icemac** [comment]
Let's see what 3.12b2 has to offer.

**Comment by icemac** [comment]
The result for ubuntu in GHA is:

```
Tests with errors:
   test_DT_Try__Try__02 (DocumentTemplate.tests.test_DT_Try.DT_Try_Tests.test_DT_Try__Try__02)
   test_DT_Try__Try__06 (DocumentTemplate.tests.test_DT_Try.DT_Try_Tests.test_DT_Try__Try__06)
   test_DT_Try__Try__07 (DocumentTemplate.tests.test_DT_Try.DT_Try_Tests.test_DT_Try__Try__07)
   test_menu_dtml__2 (App.tests.test_ApplicationManager.MenuDtmlTests.test_menu_dtml__2)
   test_Image__manage_main__3 (OFS.tests.testFileAndImage.FileEditTests.test_Image__manage_main__3)
Total: 3245 tests, 0 failures, 5 errors, 37 skipped in 23.223 seconds.
```

That's way better but also a bit surprising, that DTML tests fail.

**Comment by icemac** [comment]
Locally I seem to get the same 5 errors + lots of deprecation warnings. So clearly a step forward.

**Comment by dataflake** [comment]
My "broken" Python 3.12 is the result of virtualenv (via tox) installing pip version 22.3.1 into the Python 3.12 virtual environment. Pip 22.3.1 is not compatible with Python 3.12. The solution is to use environment variables inside tox.ini `testenv` to force a newer pip:

```
[testenv]
+setenv =
+    py312: VIRTUALENV_PIP=23.1.2
+    py312: PIP_REQUIRE_VIRTUALENV=0
```

Question: I can simply add this in `.meta.toml` here, or I can add it to the template file in the `meta` repository itself. I am sure others will run into the same issue.

**Comment by icemac** [comment]
@dataflake Do you have a clue why tox uses an outdated pip version? Do you use a current `tox` version and is there a current `pip` installed in the `venv` where `tox` is installed?

I'd like to find out why this problem does not happen to me and I'd like to get around stuffing a hard coded version number into a config file.

If we do not find out the cause of the problem I think your changes should got into `meta/config` so they can be changed in one place instead of having it in several `.meta.toml` files.

**Comment by icemac** [comment]
@dataflake Okay, let's move this fix into `meta/config` until there is new enough version of `virtualenv` released.

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
The test failures under Python 3.12 are actually a zope.testrunner issue: https://github.com/zopefoundation/zope.testrunner/issues/149

**Comment by dataflake** [comment]
I just confirmed that these errors are fixed with https://github.com/zopefoundation/zope.testrunner/pull/150 applied.

**Comment by dataflake** [comment]
This PR will go green when zope.testrunner 6.1 is on PyPI and pinned here, I'm just waiting for the required privileges.

**Comment by dataflake** [comment]
The last remaining failure looks like a tox issue to me

**Comment by icemac** [comment]
https://github.com/zopefoundation/Zope/pull/1129/commits/47d82b255560f0967f0e1af13a50c11aeab41b3b has to be ported to `.meta.toml` so it is not lost on the next meta/config run.

**Comment by dataflake** [comment]
> [47d82b2](https://github.com/zopefoundation/Zope/commit/47d82b255560f0967f0e1af13a50c11aeab41b3b) has to be ported to `.meta.toml` so it is not lost on the next meta/config run.

Done.

**Comment by dataflake** [comment]
I have removed the tags, IMHO this is ready to be merged.

**Comment by icemac** [comment]
Thank you for working on this PR. 😃
After it has been merged I'd like to cut a new Zope 5 release.

**Comment by dataflake** [comment]
Fine by me. Do you want me to do it? I have time this morning.

**Comment by icemac** [comment]
> Fine by me. Do you want me to do it? I have time this morning.

This would be very helpful as I'd would try to do it tomorrow. (Could you in the announcement please also mention the Zope 4.8.9 release fixing the same security issues?)

**Comment by dataflake** [comment]
Yes, will do.

**Comment by icemac** [comment]
@dataflake Thank you very much!

**Pull request merged**
