### PR TITLE
Fixes for Plone/Archetypes

### PR DESCRIPTION
**Pull request by d-maurer**
This PR fixes issues discovered by Maurits van Rees in relation to Plone 5.2 under Python 2 and Archetypes.

Specifically: it requires now zope.tales >= 5.0.2 (which fixes the Plone 5.2 problems) and it enhances the fidelity of the "chameleon --> zope.tales" context wrapper to support Archetypes frame inspection and template variable injection.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
All Plone 5.2 tests pass with this branch on Python 2.7, 3.6 and 3.7. Great!
For me it is fine to merge.

**Comment by d-maurer** [comment]
Maurits van Rees wrote at 2020-3-30 14:13 -0700:
>All Plone 5.2 tests pass with this branch on Python 2.7, 3.6 and 3.7. Great!

Thank you for your testing!

>For me it is fine to merge.

I will merge tomorrow.

**Comment by d-maurer** [comment]
@dataflake Could you make a new release please (to make the fixes for Plone/Archetypes easily available).

**Comment by dataflake** [comment]
**After** #807 is merged you mean, right? When that's done I can make a release, yes.

**Comment by dataflake** [comment]
Oh sorry I got confused with all these PRs. This was 4.x, the other was master, and there's no connection. I'll look at it later.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-3-30 23:03 -0700:
>Oh sorry I got confused with all these PRs. This was 4.x, the other was master, and there's no connection. I'll look at it later.

I have merged #812 into "master", too.

I am not sure whether we already want a new Zope 5 release.

**Comment by dataflake** [comment]
I don't think we do. I will leave that up to Michael.

**Comment by mauritsvanrees** [comment]
Thanks all, especially @d-maurer !
A 4.x release is welcome, but for the moment we are using a checkout of the branch in 5.2. No rush, maybe some more dust needs to settle. I do want to go for a 5.2 release in April.

**Pull request merged**
