### PR TITLE
Add preliminary support for Python 3.11.

### LINKED ISSUE #992: Add support for Python 3.11
As of Python 3.11.0a7 we have the following problems:

- [X] https://github.com/zopefoundation/ExtensionClass/issues/37 – Fix released in version 4.6
- [x] https://github.com/zopefoundation/Persistence/issues/28 – Fix released in version 3.3
- [x] https://github.com/zopefoundation/Acquisition/issues/59 – no release necessary
- [x] https://github.com/zopefoundation/RestrictedPython/issues/222 - Fix released as 5.3a1.dev0
- [x] https://github.com/zopefoundation/AccessControl/issues/122
- [x] https://github.com/zopefoundation/zodbpickle/pull/65
- [x] https://github.com/zopefoundation/zope.container/issues/40

Next steps:

- [ ] Run `meta/config` on `Zope` an allow future python versions. (#1030)

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [x] Await for 3.11.0a7 on GHA
- [x] Await for zodbpickle release supporting Python 3.11 (https://github.com/zopefoundation/zodbpickle/pull/65)
- [x] Update to use zodbpickle release.
- [x] Allow to use the RestrictedPython dev-pre-release
- [x] Await for zope.container release supporting Python 3.11 (https://github.com/zopefoundation/zope.container/pull/44)
- [x] Update to use zope.container release.

Fixes #992

### CODE REVIEW

**Comment by dataflake** [comment]
Two issues:

- It looks like `versions-prod.cfg` wants to pull  the alpha of `RestrictedPython` for Python 3.10. That's not right, correct?
- There seems to be an issue with the requirements file generation. They show the alpha of `RestrictedPython` for anything higher than Python 3.6.

**Comment by dataflake** [comment]
I have fixed the versions issues and the requirements file generation scripts, as far as I am concerned this is ready for merging into `master`.

**Review by dataflake — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Is there any chance to get this merged? Maybe without actually activating the 3.11 tests, if that is unwanted? This would make it easier to start testing Plone on 3.11 as well. I am asking because since a few days we can test [3.11 on our Jenkins server](https://jenkins.plone.org/job/plone-6.0-python-3.11/). It fails at `zope.container`, which is pinned to a correct version in this PR.

There is no need to rush things, I am not in a hurry. In Plone we still even need to fix a few things in our testing setup to properly test all PRs on Python 3.10, so if 3.11 takes longer that is okay. I am already happy that we can ship Plone 6 this fall with Python 3.10 support, due to all the hard work from the Zope community. Just wondering how much work 3.11 would be, and a merge here would help.
(Just thinking: I could probably change our Zope checkout on Python 3.11 to use this PR branch, presuming buildout already understands this.)

BTW, I am [running a poll](https://community.plone.org/t/plone-6-0-drop-support-for-python-3-7-and-3-8/15549?u=mauritsvanrees) to see which Python versions people expect Plone 6 to support. It seems likely we will drop 3.7. Python 3.8 is on the fence.

**Comment by icemac** [comment]
I tried it with Python 3.10 and `buildout` and it worked, so I merged the PR.

**Comment by mauritsvanrees** [comment]
Thanks!

**Comment by mauritsvanrees** [comment]
Any chance to get a Zope release with this today? Or are some releases of other packages still needed first?

I may do a Plone 6 beta 2 today, if I manage to finish a few things. I can manage without a Zope release, sticking to 5.5.2, but if it is there I can include it.

**Comment by dataflake** [comment]
My only concern would be that people assume Python 3.11 is now officially supported. It's not, at least until RestrictedPython has been reviewed fully to prevent security issues with Python 3.11.

If it was up to me I would change the wording of the change log entry from "Add preliminary support for Python 3.11 (as of 3.11.0b5)." to "Started work on Python 3.11 support." or something similarly careful. And you as Plone release manager should make sure that you're not making any premature promises about Python 3.11 support other than "it's coming, we're working on it".

@icemac what do you think?

**Comment by icemac** [comment]
@dataflake I second changing the change log to a more careful wording.

**Comment by icemac** [comment]
@mauritsvanrees I do not think that other packages have to be released beforehand. At least `buildout.cfg` does not do any source checkouts.

**Comment by dataflake** [comment]
OK, I'll change the change log and do the release this morning.

**Comment by mauritsvanrees** [comment]
Thank you!

**Pull request merged**
