### PR TITLE
fix for #44 on 2.13 branch.

### PR DESCRIPTION
**Pull request by gweis**

### CODE REVIEW

**Comment by gweis** [comment]
Something seems to go wrong with some i18n tests. I had this issue on my local machine as well.
However, this problem only occurred when running the tests via ./bin/test. Using ./bin/alltests had no test failures at all.

**Comment by tseaver** [comment]
I just reverted the commit, 5ed84400dbde8f5ebd10b00e1df76871e7363753, which broke the tests on the 2.13 branch.  Can you please rebase against the 2.13 branch and re-push?

**Comment by tseaver** [comment]
Thanks for the patch!

**Comment by gweis** [comment]
Sorry for the late reply... do you still want me to rebase? Seems like it is already merged. (and sorry for forgetting about the changelog entry)

**Comment by tseaver** [comment]
No worries.  I merged it as part of making the 2.13.24 release.

**Pull request merged**
