### PR TITLE
Add preliminary support for Python 3.9a4.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by dataflake** [comment]
Great idea. I was thinking of that this morning, too. Travis may be the biggest problem, as always...

**Comment by icemac** [comment]
After fixing `pip` the current error is: 
```
Traceback (most recent call last):
1007  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/__init__.py", line 18, in <module>
1008    from AccessControl.Implementation import setImplementation
1009  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/Implementation.py", line 99, in <module>
1010    setImplementation(_default_implementation)
1011  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/Implementation.py", line 53, in setImplementation
1012    from AccessControl import ImplC as impl  # NOQA
1013  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/ImplC.py", line 26, in <module>
1014    from AccessControl.ImplPython import SecurityManager
1015  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/ImplPython.py", line 44, in <module>
1016    from AccessControl.ZopeGuards import guarded_getitem  # NOQA
1017  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/ZopeGuards.py", line 33, in <module>
1018    from AccessControl.SecurityInfo import secureModule
1019  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/AccessControl-4.1-py3.9-linux-x86_64.egg/AccessControl/SecurityInfo.py", line 45, in <module>
1020    from Persistence import Persistent
1021  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/Persistence-3.0-py3.9-linux-x86_64.egg/Persistence/__init__.py", line 60, in <module>
1022    from Persistence.mapping import PersistentMapping  # NOQA
1023  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/Persistence-3.0-py3.9-linux-x86_64.egg/Persistence/mapping.py", line 74, in <module>
1024    class PersistentMapping(with_metaclass(
1025  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/Persistence-3.0-py3.9-linux-x86_64.egg/Persistence/mapping.py", line 70, in __new__
1026    return meta(name, bases, d)
1027  File "/home/travis/build/zopefoundation/Zope/.tox/py39/eggs/Persistence-3.0-py3.9-linux-x86_64.egg/Persistence/mapping.py", line 31, in __new__
1028    return ExtensionClass.__new__(cls, *args, **kw)
1029TypeError: multiple bases have instance lay-out conflict
```

It does not happen locally with the same Python version.
I am out for now.

**Comment by dataflake** [comment]
For what it's worth, I can confirm the tests on Python 3.9 run fine in my macOS sandbox.

**Comment by icemac** [comment]
@dataflake Same here. My next steps will be to try AccessControl, ExtensionClass, Persistence, persistent on TravisCI for 3.9 to see if it breaks there, too.

**Comment by dataflake** [comment]
On a CentOS 7 install the tests run through without issue. The Python interpreter was compiled with `--enable-optimizations`, nothing else.

**Comment by icemac** [comment]
This has to do with https://github.com/zopefoundation/persistent/issues/124 and https://github.com/zopefoundation/Persistence/issues/22. These issues seem to have been fixed before we can use Python 3.9. So moving the issue to future after Zope 5.0. Preliminary Python 3.9 support should not prevent the Zope 5 release.

**Comment by dataflake** [comment]
I fully agree.

**Pull request merged**
