### PR TITLE
Use func_code if __code__ is None.

### PR DESCRIPTION
**Pull request by MrTango**
See also https://github.com/zopefoundation/zope.publisher/pull/10

### CODE REVIEW

**Comment by hannosch** [comment]
Based on the discussion in zope.publisher it seems this was a workaround, which is no longer needed if the old code using `func_code` / `im_func` is updated to use `__code__` / `__func__`.

As far as I know everything in Zope 4.0 (incl. PythonScripts) has been changed, so this workaround shouldn't be needed anymore.

**Comment by icemac** [comment]
@hannosch This PR seems to be another way to fix the same issue I am trying to fix in zopefoundation/Products.PythonScripts#12. It can only happen for PythonScript instances which where created before Zope 4.

@MrTango Does this PR only target Products.PythonScripts or are there  other cases where `func_code` might still exists persistently?

**Comment by MrTango** [comment]
@icemac @hannosch better ask the original authors of the change in https://github.com/zopefoundation/zope.publisher/pull/10

**Comment by hannosch** [comment]
The zope.publisher bug mentions this as workarounds for changes required by Products.CMFCore, which are supposedly fixed on a plone-zope4 branch with zopefoundation/Products.CMFCore@0c9e66ddf31c90c3f0e60bf9c6a174c2462272c4.

But the same changes have independently been done on master as well (zopefoundation/Products.CMFCore@bce846dc9db71eb34f079ceaf80aa7dd75c836a4).

At least for newly created, non-persistent objects, I'd rather like to avoid falling back to any `func_` attributes. Inline migration code for persistent objects is something else. But that should be done in the persistent objects in question, not generally in the publisher code.

**Comment by icemac** [comment]
As this does not seem to be needed any longer I am closing it now.

**Pull request closed without merging**
