### PR TITLE
facelifted Zope logo

### PR DESCRIPTION
**Pull request by drfho**
Hi 
please take a look at the logo facelift.  There is a technical description, how the logo is built:
https://github.com/zopefoundation/Zope/tree/logo-facelift/src/zmi/styles/resources/logo

Looking forward to your feedback
Frank

### CODE REVIEW

**Comment by dataflake** [comment]
As someone who is mostly talent-free when it comes to graphics and front-end design I think this is super cool. Would it make sense to add fullsize logos that only contain the circle-z in the various colors and not the text?

**Comment by jugmac00** [comment]
@drfho, thanks a lot for your work! Looks real fresh!

Though, I still like the blue tone of the current logo better, but I think it will just take some time to get used to it. :+1:

**Review by dataflake — APPROVED** [review]
Really cool stuff. I like it.

**Review by icemac — APPROVED** [review]
I absolutely like it! Thank you for the time and energy put into it.

Maybe we could add a change log entry to announce the logo facelift there, too.

**Comment by jensens** [comment]
Wow, great work! Besides that I want it, I also like the description of the construction process of the Z-symbol :)

**Comment by dataflake** [comment]
I'd like to make use of the logos so I'll go ahead and merge this now

**Comment by dataflake** [comment]
I also merged this into the 4.x branch, by the way

**Pull request merged**
