### PR TITLE
#1109 docs ja translation

### PR DESCRIPTION
**Pull request by techtake**
I translated the document into Japanese. See the detail in #1109.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Comment by techtake** [comment]
Thank you for the cleanup and creating the document how to work on translating.  Now I merge this branch into the master branch.

**Comment by techtake** [comment]
One of the tests failed (see the detail at https://github.com/zopefoundation/Zope/actions/runs/4486163434/jobs/7888395325#step:6:36). But the reason of the failure seemed to be not caused by source codes. So, I rerun the failed test. It passed.

**Comment by dataflake** [comment]
If you go to https://zope.readthedocs.io/, where the documentation is automatically published with every push to GitHub, you will get the default English version at https://zope.readthedocs.io/en/latest/ and the Japanese version at https://zope.readthedocs.io/ja/latest/. When you click on the version selector at the bottom left ("v: latest") the little popup now shows links for switching between languages.

**Comment by techtake** [comment]
I was able to switch languages, following your instruction. I will continue to translate.

**Pull request merged**
