### PR TITLE
Fixing fixing `allowed_attributes` - Raise HTTP-401

### LINKED ISSUE #397: BrowserViews implement IPublishTraverse in Zope 4 which breaks allowed_attributes and allowed_interface
In Zope 4 a `BrowserView` always implements `IPublishTraverse` which it did not in Zope 2.
This breaks the way to make methods traveseable using `allowed_attributes` and `allowed_interface` in zcml. 

Example:

```xml
  <browser:page
      name="foo"
      for="*"
      class=".dummy.Foo"
      permission="zope2.View"
      allowed_attributes="bar"
      />
```
dummy.py:

```python
from Products.Five import BrowserView

class Foo(BrowserView):

    def __call__(self):
        return 'foo'

    def bar(self):
        """bar"""
        return 'foobar'
```

In Zope 2 (Plone 5.1) http://0.0.0.0:8080/Plone/foo/bar returned `foobar`. In Zope 4 (Plone 5.2) that throws a 404.

The relavant code is in `BaseRequest.traverseName`:

```python
if IPublishTraverse.providedBy(ob):
    ob2 = ob.publishTraverse(self, name)
else:
    adapter = queryMultiAdapter((ob, self), IPublishTraverse)
    if adapter is None:
        # Zope2 doesn't set up its own adapters in a lot of cases
        # so we will just use a default adapter.
        adapter = DefaultPublishTraverse(ob, self)

    ob2 = adapter.publishTraverse(self, name)
```

In Zope 4 `IPublishTraverse.providedBy(ob)` is true for all BrowserViews because in https://github.com/zopefoundation/Zope/blob/master/src/Products/Five/browser/metaconfigure.py#L145 the class `zope.browserpage.metaconfigure.simple` is injected in the `bases` of each `BrowserView`. Since `Foo` has no `publishTraverse` of its own the one from `simple` is called which then raises `NotFound`.

The `mro` looks like this before the injection:

```
(Pdb++) pp ob.__class__.__mro__
(<class 'Products.CMFPlone.browser.dummy.Foo'>,
 <class 'Products.Five.browser.BrowserView'>,
 <class 'zope.publisher.browser.BrowserView'>,
 <class 'zope.location.location.Location'>,
 <class 'object'>)
```

And like this after it:
```
(Pdb++) pp ob.__class__.__mro__
(<class 'Products.Five.browser.metaconfigure.Foo'>,
 <class 'Products.CMFPlone.browser.dummy.Foo'>,
 <class 'Products.Five.browser.BrowserView'>,
 <class 'Products.Five.browser.metaconfigure.simple'>,
 <class 'zope.browserpage.metaconfigure.simple'>,
 <class 'zope.publisher.browser.BrowserView'>,
 <class 'zope.location.location.Location'>,
 <class 'object'>)
```

@jaroel and me were trying to figure out a solution but we require help. 

*This issue is a replacement for the original ticket https://github.com/plone/Products.CMFPlone/issues/2624 which I moved to Zope since it is not directly related to Plone.*

### PR DESCRIPTION
**Pull request by icemac**
Fixes #397.

This PR is #610 but whit the difference that HTTP-401 is returned for attributes which are not in `allowed_attributes`.

In my mind this is the easiest solution if we can decide that HTTP-401 is a valid enough status code for this case.

### CODE REVIEW

**Comment by icemac** [comment]
@pbauer @MatthewWilkes could you please test this branch against Plone?

**Comment by pbauer** [comment]
This has the same issues as mentioned in https://github.com/zopefoundation/Zope/pull/610#issuecomment-496113775. Adding portlets and content-rules is broken as well as changing a folders view.

**Comment by icemac** [comment]
This PR can be closed when #643 got successfully merged.

**Comment by icemac** [comment]
No it can be closed now, as it is a dead end.

**Pull request closed without merging**
