### PR TITLE
Apply hotfix 20160419 [to 2.13]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Plus remove a few extra docstrings.
Probably more can be found that are safe and good to remove, but this is a nice start.

### CODE REVIEW

**Comment by leorochael** [comment]
+1

**Comment by tseaver** [comment]
Hmm, making a bunch of security-aware methods non-URL-accessible might have some backward-compatibility issues.  Is there a discussion of the threat model underlying the Plone hotfix somewhere?  The `zope-security` mailing list didn't receive any notice of the change.

**Comment by mauritsvanrees** [comment]
This is a minor part of the Plone hotfix. If this was the only part, we probably would not have issued a hotfix. But we got a question about this and since we were creating one for more serious stuff, we thought we might as well include this. We have had more hotfixes which simply removed docstrings from methods that should not have had them, so I am in the mood for shooting docstrings. :-)

The 'threat model' here is basically: an attacker can use these methods to get information about a site, which might, potentially, point to a direction of attach. For example, when you can access `Type`, an attacker may say: ah, this is a Document, let's try attack D, and on this News Item let's try attack N. Probably the `Type` is somewhere in the html code, for example a class `document` on the body, but if not: let's not give potential attackers info that they have no business knowing.

**Comment by hannosch** [comment]
Closed/merged via #63.

**Pull request closed without merging**
